### ISSUE TITLE
Multiple "opponents"

### ISSUE THREAD

**Issue by AngelofSilence** [WhiteHalmos/rgkit#111]
I see that we now have support for more than two robots in a match! 
Something I immediately noticed, though, is that it seems to be setup for a one "owner" bot and multiple opponents. Do the "opponents" consider each other as the same team? If not, wouldn't it be slightly more logical to not designate any "opponent" or "owner" bots, instead allowing just a list of what robots to use? The current setup, assuming "opponent" bots don't share a team seems lopsided towards a single game mode, so to speak, and at first sight, doesn't seem to lend itself to a pure "arena" type setup.

**Comment by WhiteHalmos** [comment]
The current workflow is optimized for developing a single bot while measuring performance against several opponents, rather than an arena setup. I'd say an arena setup is a totally different use case.

If you'd still want to work on something like that, please create an issue and patches welcome here: https://github.com/RobotGame/rgkit/issues
